# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: nuget
    directory: "/"
    registries:
      - public-nuget
    schedule:
      interval: weekly
      day: thursday
      time: "12:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 15
    groups:
      AspNetCoreHealthChecks:
        patterns:
          - "AspNetCore.HealthChecks*"
      AspNetCore:
        patterns:
          - "Microsoft.AspNetCore*"
      MicrosoftExtensions:
        patterns:
          - "Microsoft.Extensions*"
      EntityFrameworkCore:
        patterns:
          - "Microsoft.EntityFrameworkCore*"
      OpenTelemetry:
        patterns:
          - "OpenTelemetry*"
      MicrosoftDotNet:
        patterns:
          - "Microsoft.DotNet*"
      Polly:
        patterns:
          - "Polly.*"
      Serilog:
        patterns:
          - "Serilog*"
      Tests:
        patterns:
          - "Microsoft.NET.Test*"
          - "xunit*"
      All:
        patterns:
          - "*"
    labels:
      - "area-codeflow"

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    # Workflow files stored in the default location of `.github/workflows`
    # You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.
    directory: '/'
    schedule:
      interval: 'weekly'
      day: thursday
      time: "12:00"
      timezone: "Europe/Moscow"
    open-pull-requests-limit: 5
    labels:
      - area-engineering-systems
